Database:
  bucket: "kpmgybigta"
  key: "config/db_config.json"
SQS:
  request:
    text: "https://sqs.ap-northeast-2.amazonaws.com/475985888665/text"
    photo: "https://sqs.ap-northeast-2.amazonaws.com/475985888665/vision"
    call: "https://sqs.ap-northeast-2.amazonaws.com/475985888665/audio"
    video: "https://sqs.ap-northeast-2.amazonaws.com/475985888665/video"
  result:
    text: "https://sqs.ap-northeast-2.amazonaws.com/475985888665/result_text"
    photo: "https://sqs.ap-northeast-2.amazonaws.com/475985888665/result_photo"
    call: "https://sqs.ap-northeast-2.amazonaws.com/475985888665/result_call"
Columns:
  project: ["type", "registered_time", "status"]
  job_call: ["project_id", "request_time", "create_date_time", "type", "status", "data"]
  job_text: ["project_id", "request_time", "create_date_time", "type", "status", "content"]
  job_photo: ["project_id", "request_time", "create_date_time", "type", "status", "img_url"]
  result_call :
  result_text:
  result_photo:
